language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - 14.15.3

git:
    depth: false
    
before_script :
 - curl -o- -L https://yarnpkg.com/install.sh | bash -s
 - export PATH=$HOME/.yarn/bin:$PATH
 - yarn install

addons:
  apt:
   update: true
   packages: 
      - build-essential 
      - npm 
      - nvm install node
      - node -v
      - npm i -g yarn
      

