language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - 10

git:
    depth: false

addons:
  apt:
   update: true
   packages: 
      - build-essential 
      - npm 

script:
  - npm test
  - yarn precommit
