language: node_js
arch:
  - amd64
  - ppc64le
node_js:
- '10.23'
install:
- npm install grunt-cli bower
- npm install
script:
- npm test
sudo: false
cache:
  directories:
  - esvm
  - node_modules
  - src/kibana/bower_components
